name: Daily Job Scrape

on:
  schedule:
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests beautifulsoup4 pandas
      - run: python scraper.py
      - uses: actions/upload-artifact@v4
        with:
          name: jobs-csv
          path: jobs_output.csv  # Fixed name
